version = 0.1
[default.deploy.parameters]
stack_name = "nvidia-2hr-hack"
resolve_s3 = true
s3_prefix = "nvidia-2hr-hack"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
